services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-kraft
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-kraft:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - mynetwork
    command: >
      bash -c "
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          echo 'Formatting Kafka storage...'
          CLUSTER_ID=$$(kafka-storage random-uuid)
          kafka-storage format -t $${CLUSTER_ID} -c /etc/kafka/kraft/server.properties
        fi
        kafka-server-start /etc/kafka/kraft/server.properties
      "

networks:
  mynetwork:
    driver: bridge

volumes:
  kafka-data: